### ISSUE TITLE
cargo embed --release causes defmt version mismatch

### ISSUE THREAD

**Issue by nvsd** [rp-rs/rp2040-project-template#57]
when running `cargo embed --release` I get the error 

```
Error defmt wire format version mismatch: firmware is using 3, `probe-run` supports 4
suggestion: use a newer version of `defmt` or `cargo install` a different version of `probe-run` that supports defmt 3
```
Which is pretty weird because those versions seem wrong anyways?

Not quite sure what's going on here.

**Comment by 9names** [comment]
Cargo-embed has an error message mentioning probe-run? I never noticed that before.
Anyway, this is documented here https://github.com/rp-rs/rp-hal/issues/581

I thought we fixed it in the template...

**Comment by nvsd** [comment]
Sorry, just to clarify I'm talking about cargo embed specifically. It seems like the fixes in the template were focused around probe run only. 

I got the fix from a probe-rs matrix user which is to run `cargo install --locked --force cargo-embed`.

I'm happy to open a PR to update the readme I'm not quite sure where or how you'd like to word that though considering it's temporary and could be fixed any day now.

**Comment by jannic** [comment]
I'd just update the example to read `cargo install --locked cargo-embed`. Even if the fix is only needed temporarily, using the `--locked` flag seems to be a good idea in general, as discussed on matrix.

Not 100% sure about the `--force` flag, but I think I won't add it to the README. You only need it if you already installed the binary without the `--locked` flag, and you get a helpful message in that case: `Ignored package `cargo-embed v0.18.0` is already installed, use --force to override`.
